@echo off
REM Confession Slice - Setup Helper Script (Windows)
REM This script helps you set up environment variables for Firebase

echo 🍕 Confession Slice - Firebase Setup Helper
echo ===========================================
echo.
echo This script will help you create a .env file for Firebase.
echo You'll need your Firebase credentials from Firebase Console.
echo.
echo Get your config from:
echo https://console.firebase.google.com/ - Your Project - Settings - SDK setup and configuration
echo.

REM Check if .env already exists
if exist .env (
    echo ⚠️  .env file already exists!
    set /p overwrite="Do you want to overwrite it? (y/N): "
    if /i not "%overwrite%"=="y" (
        echo ❌ Setup cancelled.
        exit /b 0
    )
)

echo.
echo Please enter your Firebase configuration:
echo.

set /p api_key="API Key: "
set /p auth_domain="Auth Domain: "
set /p project_id="Project ID: "
set /p storage_bucket="Storage Bucket: "
set /p sender_id="Messaging Sender ID: "
set /p app_id="App ID: "

REM Create .env file
(
echo # Firebase Configuration
echo # Generated by setup script
echo VITE_FIREBASE_API_KEY=%api_key%
echo VITE_FIREBASE_AUTH_DOMAIN=%auth_domain%
echo VITE_FIREBASE_PROJECT_ID=%project_id%
echo VITE_FIREBASE_STORAGE_BUCKET=%storage_bucket%
echo VITE_FIREBASE_MESSAGING_SENDER_ID=%sender_id%
echo VITE_FIREBASE_APP_ID=%app_id%
) > .env

echo.
echo ✅ .env file created successfully!
echo.
echo Next steps:
echo 1. Run: npm run dev
echo 2. Open: http://localhost:5174
echo 3. Test real-time sync in multiple browser windows
echo.
echo To deploy to Vercel:
echo 1. Run: vercel
echo 2. Add these environment variables to Vercel Dashboard
echo 3. See VERCEL_DEPLOYMENT.md for details
echo.
echo Happy confessing! 🎉
pause
