#!/bin/bash

# Confession Slice - Setup Helper Script
# This script helps you set up environment variables for Firebase

echo "🍕 Confession Slice - Firebase Setup Helper"
echo "==========================================="
echo ""
echo "This script will help you create a .env file for Firebase."
echo "You'll need your Firebase credentials from Firebase Console."
echo ""
echo "Get your config from:"
echo "https://console.firebase.google.com/ → Your Project → Settings → SDK setup and configuration"
echo ""

# Check if .env already exists
if [ -f .env ]; then
    echo "⚠️  .env file already exists!"
    read -p "Do you want to overwrite it? (y/N): " overwrite
    if [[ ! $overwrite =~ ^[Yy]$ ]]; then
        echo "❌ Setup cancelled."
        exit 0
    fi
fi

echo ""
echo "Please enter your Firebase configuration:"
echo ""

read -p "API Key: " api_key
read -p "Auth Domain: " auth_domain
read -p "Project ID: " project_id
read -p "Storage Bucket: " storage_bucket
read -p "Messaging Sender ID: " sender_id
read -p "App ID: " app_id

# Create .env file
cat > .env << EOF
# Firebase Configuration
# Generated by setup script
VITE_FIREBASE_API_KEY=$api_key
VITE_FIREBASE_AUTH_DOMAIN=$auth_domain
VITE_FIREBASE_PROJECT_ID=$project_id
VITE_FIREBASE_STORAGE_BUCKET=$storage_bucket
VITE_FIREBASE_MESSAGING_SENDER_ID=$sender_id
VITE_FIREBASE_APP_ID=$app_id
EOF

echo ""
echo "✅ .env file created successfully!"
echo ""
echo "Next steps:"
echo "1. Run: npm run dev"
echo "2. Open: http://localhost:5174"
echo "3. Test real-time sync in multiple browser windows"
echo ""
echo "To deploy to Vercel:"
echo "1. Run: vercel"
echo "2. Add these environment variables to Vercel Dashboard"
echo "3. See VERCEL_DEPLOYMENT.md for details"
echo ""
echo "Happy confessing! 🎉"
